const namespaceStrings = {
  title: 'Namespaces',
  detailsTitle: 'Namespace',
  walletSection: 'Wallet',
  actionsSection: 'Actions',
  namespacesSection: 'Owned namespaces',
  entriesSection: 'Key/value entries',
  selectWallet: 'Select a wrapped SegWit wallet',
  noWallets: 'Create or import a writable wrapped SegWit wallet to manage namespaces.',
  create: 'Create namespace',
  refresh: 'Refresh namespaces',
  loading: 'Loading namespaces…',
  empty: 'No namespaces found in this wallet.',
  createTitle: 'Create namespace',
  createPrompt: 'Enter a display name for the namespace.',
  addKey: 'Add key/value',
  updateKey: 'Update value',
  deleteKey: 'Delete a key',
  transfer: 'Transfer namespace',
  refreshEntries: 'Refresh entries',
  keyPrompt: 'Enter a key.',
  valuePrompt: 'Enter a value.',
  deletePrompt: 'Enter the key to delete.',
  transferPrompt: 'Enter the destination wrapped SegWit address.',
  namespaceId: 'Namespace ID',
  copyNamespaceIdHint: 'Copies the complete namespace ID to the clipboard.',
  ownerAddress: 'Control address',
  confirmTitle: 'Confirm namespace transaction',
  confirmFee: (fee: number) => `Network fee: ${(fee / 100_000_000).toFixed(8)} WIII`,
  successTitle: 'Success',
  networkError: 'Unable to connect to the configured Electrum server.',
  broadcastSuccess: 'Namespace transaction broadcast successfully.',
  createSuccess: (namespaceId?: string) =>
    namespaceId ? `Namespace transaction broadcast. New namespace ID: ${namespaceId}` : 'Namespace transaction broadcast successfully.',
  transferSuccess: 'Namespace transfer transaction broadcast successfully.',
  deleteConfirm: (key: string) => `Delete “${key}” from this namespace?`,
  transferConfirm: (address: string) => `Transfer control of this namespace to ${address}?`,
  errorTitle: 'Namespace error',
  rpcUnavailable: 'The configured ElectrumX server does not provide Wiiicoin namespace RPC methods.',
  writableWalletRequired: 'Namespaces require a writable wrapped SegWit wallet.',
  entriesEmpty: 'No key/value entries were returned for this namespace.',
  transferMarker: 'Namespace transfer',
  unconfirmed: 'Unconfirmed',
};

export default namespaceStrings;
